# Generated by Django 4.2.2 on 2023-06-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Firma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv_firme", models.CharField(max_length=50)),
                ("opis", models.CharField(max_length=200)),
                ("industrija", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Posao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv_posla", models.CharField(max_length=50)),
                ("opis_posla", models.CharField(max_length=1000)),
                ("placa", models.PositiveBigIntegerField()),
                ("lokacija", models.CharField(max_length=50)),
                ("kontakt_osobe", models.EmailField(max_length=50)),
                (
                    "firma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.firma",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="localization",
            name="country",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="company",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="level",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="localization",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="position",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="requirements",
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Level",
        ),
        migrations.DeleteModel(
            name="Localization",
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="Requirements",
        ),
    ]
