# Generated by Django 4.2.2 on 2023-06-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_firma_posao_remove_localization_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firma",
            options={
                "ordering": ("naziv_firme",),
                "verbose_name": "Firma",
                "verbose_name_plural": "Firme",
            },
        ),
        migrations.AlterModelOptions(
            name="posao",
            options={
                "ordering": ("naziv_posla",),
                "verbose_name": "Posao",
                "verbose_name_plural": "Poslovi",
            },
        ),
    ]
