# Generated by Django 4.2.2 on 2023-06-19 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_firma_options_alter_posao_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="posao",
            name="datum_izrade",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
