# Generated by Django 4.2.2 on 2023-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_posao_datum_izrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="firma",
            name="image",
            field=models.ImageField(default="./images/a.jpg", upload_to="./images"),
        ),
        migrations.AddField(
            model_name="posao",
            name="image",
            field=models.ImageField(default="./images/a.jpg", upload_to="./images"),
        ),
    ]
