# Generated by Django 4.2.2 on 2023-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_firma_image_posao_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firma",
            name="image",
            field=models.ImageField(default="images/a.jpg", upload_to="./images"),
        ),
        migrations.AlterField(
            model_name="posao",
            name="image",
            field=models.ImageField(default="images/a.jpg", upload_to="images"),
        ),
    ]
