# Generated by Django 4.2.2 on 2023-06-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_firma_image_alter_posao_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firma",
            name="image",
            field=models.ImageField(default="images/default.png", upload_to="./images"),
        ),
        migrations.AlterField(
            model_name="posao",
            name="image",
            field=models.ImageField(default="images/default.png", upload_to="images"),
        ),
    ]
