# Generated by Django 4.2.2 on 2023-06-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_firma_image_alter_posao_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posao",
            name="opis_posla",
            field=models.TextField(),
        ),
    ]
